# Here lie dragons!
#
# This action either builds the server or
# builds a paperclip jar to be updated in the body
# of the PR relating to this action.

on:
  workflow_dispatch:
    branches:
      - main
      - update/1.21.5

jobs:
  build:
    # The goal of the build workflow is split into multiple requirements.
    # 1. Run on pushes to same repo.
    # 2. Run on PR open/reopen/syncs from repos that are not the same (PRs from the same repo are covered by 1)
    # 3. Run on labeled PRs that have the build-pr-jar flag.
    if: >
      (
        (github.event_name == 'push')
        || (github.event_name == 'pull_request' && github.repository != github.event.pull_request.head.repo.full_name && contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action))
        || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'build-pr-jar')
      )

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: true
    steps:
        uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{ fromJSON(steps.determine.outputs.result).pr }}
          path: paper-server/build/libs/paper-paperclip-*-mojmap.jar
